services:

  mariadb:
    image: mariadb:12

    container_name: pos-mariadb

    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: mapalo
      MARIADB_DATABASE: posdb
      MARIADB_USER: mapalo
      MARIADB_PASSWORD: mapalo

    ports:
      - "3307:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
  # pos-api:
  #   image: gradle:jdk25

  #   container_name: pos-api

  #   working_dir: /app

  #   restart: always

  #   ports:
  #     - "8080:8080"

  #   depends_on:
  #     - mariadb

  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/posdb
  #     SPRING_DATASOURCE_USERNAME: mapalo
  #     SPRING_DATASOURCE_PASSWORD: mapalo

  #   volumes:
  #     - .:/app
  #     - gradle_cache:/home/gradle/.gradle

  #   stdin_open: true
  #   tty: true

  #   command: sh -c "./gradlew classes --continuous & ./gradlew bootRun"

volumes:
  mariadb_data:
  # gradle_cache: